# Generated by Django 5.1 on 2024-08-26 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Character",
            new_name="Characters",
        ),
    ]
